spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate # create update create-update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 500
    database: mysql
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  datasource:
    url: ""
    username: ""
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ""
    port:

  mail:
    host: smtp.gmail.com
    port: 587
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000 #ms
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2

logging:
  level:
    root: error


server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 8000
jwt:
  secretKey: ""

cloud:
  aws:
    credentials:
      accessKey: ""
      secretKey: ""
    s3:
      bucket: ""
      name: "" 
    region:
      static: ""


nurigo:
  public: ""
  secret: ""
  number: ""

naver:
  X-Naver-Client-Id: ""
  X-Naver-Client-Secret: ""
